### ISSUE TITLE
variables per host in group

### ISSUE THREAD

**Issue by muelli** [MatthewMi11er/vai#4]
I want to create an inventory file like this:

```
[cdh5-zookeeperserver]
idc1-hjn1 zoo_id=1
idc1-hjn2 zoo_id=2

```

So I need to define some variables on the hosts in the group.
How would I do that with vai?

**Comment by MatthewMi11er** [comment]
@muelli have you looked into setting those in your `host_vars` folder instead.
Something like:

``` yaml
---
# file: ./host_vars/idc1-hjn1
zoo_id: 1
---
# file: ./host_vars/idc1-hjn2
zoo_id: 2
```

If you specifically need them to be generated then vai isn't currently setup to do that. Code contributions are welcome but do read what Ansible [has to say](http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data) about storing variables in your inventory file.
